const products = [
  {
    id: "001",
    name: "Smartphone XYZ",
    category: "Electronics",
    brand: "Brand A",
    price: 799.99,
    retailer: "Retailer A",
    image_url: "url_to_image_1",
    description: "A high-end smartphone with a 6.5-inch display.",
  },
  {
    id: "002",
    name: "Laptop Pro 15",
    category: "Electronics",
    brand: "Brand B",
    price: 1299.99,
    retailer: "Retailer B",
    image_url: "url_to_image_2",
    description: "A powerful laptop with Intel Core i7 and 16GB RAM.",
  },
  {
    id: "003",
    name: "Wireless Headphones",
    category: "Audio",
    brand: "Brand C",
    price: 199.99,
    retailer: "Retailer C",
    image_url: "url_to_image_3",
    description: "Noise-cancelling wireless headphones with long battery life.",
  },
  {
    id: "004",
    name: 'Gaming Monitor 27"',
    category: "Electronics",
    brand: "Brand D",
    price: 449.99,
    retailer: "Retailer A",
    image_url: "url_to_image_4",
    description: "A high-refresh-rate monitor ideal for gaming.",
  },
  {
    id: "005",
    name: "Smartwatch Pro",
    category: "Wearables",
    brand: "Brand E",
    price: 199.99,
    retailer: "Retailer D",
    image_url: "url_to_image_5",
    description: "A smartwatch with fitness tracking and heart rate monitor.",
  },
  {
    id: "006",
    name: "4K Ultra HD TV",
    category: "Electronics",
    brand: "Brand F",
    price: 799.99,
    retailer: "Retailer E",
    image_url: "url_to_image_6",
    description: "A 55-inch 4K smart TV with built-in streaming apps.",
  },
  {
    id: "007",
    name: "Bluetooth Speaker",
    category: "Audio",
    brand: "Brand G",
    price: 89.99,
    retailer: "Retailer F",
    image_url: "url_to_image_7",
    description: "Portable Bluetooth speaker with excellent sound quality.",
  },
  {
    id: "008",
    name: "Digital Camera",
    category: "Photography",
    brand: "Brand H",
    price: 599.99,
    retailer: "Retailer G",
    image_url: "url_to_image_8",
    description: "A compact camera with 20MP sensor and 4K video recording.",
  },
  {
    id: "009",
    name: "Electric Toothbrush",
    category: "Health & Personal Care",
    brand: "Brand I",
    price: 99.99,
    retailer: "Retailer H",
    image_url: "url_to_image_9",
    description:
      "Electric toothbrush with smart features for better oral care.",
  },
  {
    id: "010",
    name: "Electric Kettle",
    category: "Home Appliances",
    brand: "Brand J",
    price: 49.99,
    retailer: "Retailer I",
    image_url: "url_to_image_10",
    description: "A fast-boiling electric kettle with temperature control.",
  },
  {
    id: "011",
    name: "Air Fryer",
    category: "Home Appliances",
    brand: "Brand K",
    price: 159.99,
    retailer: "Retailer J",
    image_url: "url_to_image_11",
    description: "A healthy alternative to deep frying with this air fryer.",
  },
  {
    id: "012",
    name: "Cordless Vacuum Cleaner",
    category: "Home Appliances",
    brand: "Brand L",
    price: 199.99,
    retailer: "Retailer K",
    image_url: "url_to_image_12",
    description: "Lightweight cordless vacuum for easy home cleaning.",
  },
  {
    id: "013",
    name: "Coffee Maker",
    category: "Home Appliances",
    brand: "Brand M",
    price: 79.99,
    retailer: "Retailer L",
    image_url: "url_to_image_13",
    description: "A programmable coffee maker with multiple brew sizes.",
  },
  {
    id: "014",
    name: "Portable Power Bank",
    category: "Accessories",
    brand: "Brand N",
    price: 39.99,
    retailer: "Retailer M",
    image_url: "url_to_image_14",
    description:
      "A 10000mAh power bank to keep your devices charged on the go.",
  },
  {
    id: "015",
    name: "Smart Thermostat",
    category: "Home Automation",
    brand: "Brand O",
    price: 149.99,
    retailer: "Retailer N",
    image_url: "url_to_image_15",
    description:
      "Control your home temperature remotely with this smart thermostat.",
  },
];

export default products;
